### ISSUE TITLE
npm run start 【Error: Cannot find module 'react-awtk'】

### ISSUE THREAD

**Issue by fanzhiri** [zlgopen/react-awtk#1]
slako:demo slakofan$ npm run start

> counter@1.0.0 start
> babel-node src/index.js

internal/modules/cjs/loader.js:1088
  throw err;
  ^

Error: Cannot find module 'react-awtk'
Require stack:
- /Users/slakofan/GitHub/react-awtk/demo/src/HomePage.js
- /Users/slakofan/GitHub/react-awtk/demo/src/index.js

**Comment by xianjimli** [comment]
did you run 'npm install' correctly?
